openapi: 3.1.0
info:
  title: Archetype API
  version: 1.0.0
  description: API for accessing and managing archetypal data
servers:
  - url: "http://localhost:3000"
    description: Local development server
  - url: "https://us-central1-archetype-builder-api.cloudfunctions.net/api/"
    description: Production server

paths:
  /archetypes:
    get:
      summary: Get all archetypes
      operationId: getAllArchetypes
      tags:
        - Archetypes
      responses:
        "200":
          description: A list of all archetypes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Archetype"
        "500":
          $ref: "#/components/responses/ServerError"

  /archetypes/{name}:
    get:
      summary: Get a single archetype by name
      operationId: getArchetypeByName
      tags:
        - Archetypes
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: Name of the archetype
      responses:
        "200":
          description: Detailed information about an archetype
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Archetype"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"

  /archetypes/by-trait/{trait}:
    get:
      summary: Get archetypes by trait
      operationId: getArchetypesByTrait
      tags:
        - Archetypes
      parameters:
        - in: path
          name: trait
          required: true
          schema:
            type: string
          description: The trait to filter archetypes by
      responses:
        "200":
          description: A list of archetypes with the specified trait
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Archetype"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"

  /archetypes/by-order/{order}:
    get:
      summary: Get archetypes by order
      operationId: getArchetypesByOrder
      tags:
        - Archetypes
      parameters:
        - in: path
          name: order
          required: true
          schema:
            type: string
          description: The order to filter archetypes by
      responses:
        "200":
          description: A list of archetypes with the specified order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Archetype"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"

  /archetypes/by-thirdEye/{thirdEye}:
    get:
      summary: Get archetypes by thirdEye gemstone
      operationId: getArchetypesByThirdEye
      tags:
        - Archetypes
      parameters:
        - in: path
          name: thirdEye
          required: true
          schema:
            type: string
          description: The thirdEye gemstone to filter archetypes by
      responses:
        "200":
          description: A list of archetypes with the specified thirdEye gemstone
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Archetype"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"

  /archetypes/by-motivation/{motivation}:
    get:
      summary: Get archetypes by motivation
      operationId: getArchetypesByMotivation
      tags:
        - Archetypes
      parameters:
        - in: path
          name: motivation
          required: true
          schema:
            type: string
          description: Filter archetypes by motivation
      responses:
        "200":
          description: A list of archetypes with the specified motivation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Archetype"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"

  /archetypes/by-behavior/{behavior}:
    get:
      summary: Get archetypes by behavior
      operationId: getArchetypesByBehavior
      tags:
        - Archetypes
      parameters:
        - in: path
          name: behavior
          required: true
          schema:
            type: string
          description: To filter archetypes by behavior
      responses:
        "200":
          description: A list of archetypes with the specified behavior
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Archetype"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"

  /archetypes/by-interest/{interest}:
    get:
      summary: Get archetypes by interest
      operationId: getArchetypesByInterest
      tags:
        - Archetypes
      parameters:
        - in: path
          name: interest
          required: true
          schema:
            type: string
          description: The interest to filter archetypes by
      responses:
        "200":
          description: A list of archetypes with the specified interest
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Archetype"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"

  /archetypes/{name}/history:
    get:
      summary: Get historical examples for an archetype
      operationId: getArchetypeHistoricalExamples
      tags:
        - Archetypes
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: Name of the archetype
      responses:
        "200":
          description: Historical examples for the archetype
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/HistoricalExample"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"

  /archetypes/{name}/mythology:
    get:
      summary: Get mythological references for an archetype
      operationId: getArchetypeMythologicalReferences
      tags:
        - Archetypes
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: Name of the archetype
      responses:
        "200":
          description: Mythological references for the archetype
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MythologicalReference"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"

  /archetypes/{name}/applications:
    get:
      summary: Get practical applications for an archetype
      operationId: getArchetypePracticalApplications
      tags:
        - Archetypes
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: Name of the archetype
      responses:
        "200":
          description: Practical applications for the archetype
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"

components:
  schemas:
    Archetype:
      type: object
      properties:
        order:
          type: string
        id:
          type: string
        timestamp:
          type: string
          format: date-time
        name:
          type: string
        motto:
          type: string
        mission:
          type: string
        color:
          type: string
        planet:
          type: string
        thirdEye:
          type: string
        scores:
          type: object
          properties:
            Openness:
              type: number
            Conscientiousness:
              type: number
            Extraversion:
              type: number
            Agreeableness:
              type: number
            Neuroticism:
              type: number
        traits:
          type: array
          items:
            type: string
        motivations:
          type: array
          items:
            type: string
        behaviors:
          type: array
          items:
            type: string
        interests:
          type: array
          items:
            type: string
        historicalExamples:
          type: array
          items:
            $ref: "#/components/schemas/HistoricalExample"
        mythologicalReferences:
          type: array
          items:
            $ref: "#/components/schemas/MythologicalReference"
        practicalApplications:
          type: array
          items:
            type: string
        characteristics:
          type: object
          additionalProperties:
            type: number
        ratings:
          type: object
          additionalProperties:
            type: integer

    HistoricalExample:
      type: object
      properties:
        name:
          type: string
        description:
          type: string

    MythologicalReference:
      type: object
      properties:
        name:
          type: string
        description:
          type: string

  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
