openapi: 3.0.0
info:
  title: Archetype API
  version: 1.0.0

paths:
  /archetypes:
    get:
      summary: Get all archetypes
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Archetype"

  /archetypes/{id}:
    get:
      summary: Get archetype by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Archetype"
        404:
          $ref: "#/components/responses/NotFound"

components:
  schemas:
    Archetype:
      type: object
      properties:
        name:
          type: string
        traits:
          type: array
          items:
            type: string

  responses:
    NotFound:
      description: Archetype not found
